version: 0.2

env:
  variables:
    REGION: "us-east-1"
    VERSION_NO: "v12.21"
    IMAGE_NAME: "product-page"
    APP_NAME: "book-store-app"

phases:
  install:
    commands:
      - aws --version
      - docker --version
      - docker-compose --version
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USER --password-stdin
      - echo Logging in to Amazon ECR...
      - REPO_URI=AWS_ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com     
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPO_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${VERSION_NO:=COMMIT_HASH}
      - echo $REPO_URI
      - echo $COMMIT_HASH
      - echo $IMAGE_TAG 
  build:
    commands:
      - echo Build started on `date`
      - printenv
      - docker build -t $IMAGE_NAME .
      - docker images -a
      - echo Building the Docker image...
      - docker tag $REPO_URI/$IMAGE_NAME:latest $REPO_URI/$IMAGE_NAME:$IMAGE_TAG
      - docker images -a
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPO_URI/$IMAGE_NAME:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"topratetransferfrontend","imageUri":"%s"}]' $REPO_URI/$IMAGE_NAME:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
