version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "428819381342"
    IMAGE_REPO_NAME: "angular-album-store-product-page"
    APP_NAME: "album-store-app"
    IMAGE_TAG: "v12.21"
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    commands:
      - aws --version
      - docker --version
      - docker-compose --version
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com    
  build:
    command:
      - echo Build started on `date`
      - printenv
      - docker build -t angular-album-store-product-page .
      - docker images -a
      - echo Building the Docker image...
      - docker tag $APP_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker images -a
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 428819381342.dkr.ecr.us-east-1.amazonaws.com/angular-album-store-product-page:latest
      - echo Writing image definitions file...
      - printf '[{"name":"topratetransferfrontend","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json


